# Generated by Django 3.2.12 on 2023-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productUpdator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdatoritems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productUpdator/'),
        ),
    ]
