# Generated by Django 3.2.12 on 2022-09-04 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='model_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
