# Generated by Django 3.2.12 on 2022-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_sneaker_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='release_date',
            field=models.DateField(),
        ),
    ]
