# Generated by Django 3.2.12 on 2022-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_alter_sneaker_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='img',
            new_name='main_img',
        ),
    ]
