# Generated by Django 3.2.12 on 2022-09-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_rename_img_sneaker_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='main_img',
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sneakers/%Y/%m/%d/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sneakers.sneaker')),
            ],
        ),
    ]
