# Generated by Django 3.2.12 on 2022-09-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneakers', '0006_rename_post_images_sneaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='like_users',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='main_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/sneakers/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
