# Generated by Django 3.2.12 on 2022-10-16 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneakers', '0007_auto_20220918_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
