# Generated by Django 3.2.12 on 2023-07-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_date', models.DateTimeField(auto_now_add=True)),
                ('end_time_date', models.DateTimeField(auto_now_add=True)),
                ('date_info', models.CharField(max_length=150)),
                ('isDomestic', models.BooleanField(default=True)),
                ('isExpired', models.BooleanField(default=False)),
                ('announcement_method', models.CharField(max_length=150)),
                ('payment_method', models.CharField(max_length=150)),
                ('sale_price', models.CharField(max_length=150)),
                ('sale_price_currency', models.CharField(max_length=150)),
                ('currencySymbol', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('raffle_url', models.CharField(max_length=1000)),
                ('site_name', models.CharField(max_length=150)),
                ('shipping_method', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_infos', to='products.kicks')),
            ],
        ),
    ]
