# Generated by Django 3.2.12 on 2023-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releaseInfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseinfo',
            name='platform_pk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
