# Generated by Django 3.2.12 on 2022-12-02 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10)),
                ('shoeSize', models.CharField(choices=[('200', 200), ('205', 205), ('210', 210), ('220', 220)], default='', max_length=10)),
                ('topSize', models.CharField(choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], default='', max_length=10)),
                ('bottomSize', models.CharField(choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
