# Generated by Django 3.2.12 on 2022-11-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='spouse_name',
        ),
    ]
