# Generated by Django 3.2.12 on 2022-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bottomSize',
            field=models.CharField(choices=[('xs', 'XS'), ('sm', 'S'), ('dm', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='topSize',
            field=models.CharField(choices=[('200', 200), ('205', 205), ('210', 210), ('220', 220), ('230', 230), ('240', 240), ('250', 250), ('260', 260), ('270', 270), ('280', 280), ('290', 280), ('300', 300), ('300', 300), ('310', 310)], max_length=10),
        ),
    ]
