# Generated by Django 3.2.12 on 2022-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bottomSize',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shoeSize',
            field=models.CharField(blank=True, choices=[('200', 200), ('205', 205), ('210', 210), ('220', 220)], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='topSize',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], default='', max_length=10, null=True),
        ),
    ]
