# Generated by Django 3.2.12 on 2022-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221203_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bottomSize',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shoeSize',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='topSize',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
