# Generated by Django 3.2.12 on 2022-09-16 10:48

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bottomSize',
            field=models.CharField(choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='topSize',
            field=models.CharField(choices=[('xs', 'XS'), ('sm', 'S'), ('md', 'M'), ('lg', 'L'), ('xlg', 'XL'), ('xxlg', 'XXL'), ('xxxlg', 'XXXL')], max_length=10),
        ),
    ]
