# Generated by Django 3.2.12 on 2022-12-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221208_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/'),
        ),
    ]
