# Generated by Django 3.2.12 on 2022-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userinfo_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/images/user.png', null=True, upload_to='user/'),
        ),
    ]
