brand_list=[
# "424",
# "032c",
# "1017%20alyx%209sm",
# "2%20moncler",
# "361%20degrees",
# "3paradis",
# "5%20moncler",
# "66%20north",
# "90s%20anxiety",
# "a%20cold%20wall",
# "acne%20studios",
# "Acronym",
# "Ader%20Error",
# "Adidas",
# "Advisory%20Board%20Crystals",
# "ADYAR",
# "Afield%20Out",
# "Agolde",
# "AI%20Studios",
# "Aimé%20Leon%20Dore",
# "Air%20Jordan",
# "Alexander%20McQueen",
# "Alexander%20Wang",
# "Ambush",
# "Ami",
# "Amiri",
# "And%20Wander",
# "AND1",
# "Andersson%20Bell",
# "Angel%20Chen",
# "Anonymous%20Club",
# "Anta",
# "Anti%20Social%20Social%20Club",
# "apc",
# "AREA",
# "Ari",
# "Aries",
# "Art",
# "ASICS",
# "Awake%20NY",
# "Balenciaga",
# "Balmain",
# "Bao%20Bao%20Issey%20Miyake",
# "BAPE",
# "Baracuta",
# "bianca%20chandon",
# "Big%20Baller%20Brand",
# "Billionaire%20Boys%20Club",
# "Birkenstock",
# "BLUEMARBLE",
# "Bode",
# "Books",
# "Boris%20Bidjan%20Saberi",
# "Born%20X%20Raised",
# "Borsalino",
# "Bottega%20Veneta",
# "Brain%20Dead",
# "Brandon%20Maxwell",
# "bricks%20wood",
# "Brooks",
# "Burberry",
# "Buscemi",
# "C2H4",
# "cactus%20jack%20by%20travis%20scott",
# "Cactus%20Plant%20Flea%20Market",
# "Calvin%20Klein",
# "Camp%20High",
# "Carhartt%20WIP",
# "Cartier",
# "Casablanca",
# "Casey%20Casey",
# "Cav%20Empt",
# "CDG",
# "Cecilie%20Bahnsen",
# "CELINE",
# "Champion",
# "Chanel",
# "Charles%20Jeffrey%20Loverboy",
# "Chemist%20Creations",
# "Children%20Of%20The%20Discordance",
# "Chinatown%20Market",
# "Chloé",
# "Christian%20Louboutin",
# "Chrome%20Hearts",
# "Clarks",
# "CLOT",
# "CLOTTEE",
# "comme%20des%20garcons",
# "comme%20des%20garcons%20homme",
# "comme%20des%20garcons%20homme%20plus",
# "comme%20des%20garcons%20play",
# "comme%20des%20garcons%20shirt",
# "comme%20des%20garcons%20wallet",
# "Common%20Projects",
# "Converse",
# "Coperni",
# "courreges",
# "Craig%20Green",
# "Crocs",
# "Curry%20Brand",
# "Dc",
# "DC%20Comics",
# "Denim%20Tears",
# "Diadora",
# "diamond%20supply",
# "Dime",
# "Dior",
# "Dior%20Homme",
# "dolce%20gabbana",
# "dr%20martens",
# "Drew%20House",
# "Dries%20Van%20Noten",
# "Dutch%20Tulip%20Financial",
# "Eckhaus%20Latta",
# "Edward%20Cuming",
# "Ellesse",
# "Enfants%20Riches%20Déprimés",
# "Engineered%20Garments",
# "Entire%20Studios",
# "Eric%20Emanuel",
# "ERL",
# "ernest%20w%20baker",
# "Etonic",
# "Etudes",
# "Ewing",
"Fear%20Of%20God",
"Fear%20Of%20God%20Essentials",
"Fendi",
"Ferrari",
"Fila",
"Filling%20Pieces",
"Flatlist",
"Flight%20Club",
"Fred%20Perry",
"Gallery%20Dept.",
"GANNI",
"Gentle%20Monster",
"girls%20dont%20cry",
"Givenchy",
"Golden%20Goose",
"GOLF%20WANG",
"GR10K",
"Greg%20Lauren",
"Gucci",
"Haider%20Ackermann",
"Harley%20Davidson",
"Hatton%20Labs",
"Helmut%20Lang",
"Hender%20Scheme",
"Heron%20Preston",
"Hidden%20NY",
"Hoka%20One%20One",
"Homme%20Plissé%20Issey%20Miyake",
"Honor%20The%20Gift",
"Hood%20By%20Air",
"Human%20Made",
"Hummel%20Hive",
"Hussein%20Chalayan",
"Hyein%20Seo",
"I%20Know%20Nigo",
"Ian%20Charms",
"Icecream",
"IDEA",
"Iise",
"Issey%20Miyake",
"Jack%20Eller",
"Jacquemus",
"Jean%20Paul%20Gaultier",
"Jil%20Sander",
"John%20Geiger",
"Junya%20Watanabe",
"Junya%20Watanabe%20MAN",
"Just%20Don",
"JW%20Anderson",
"K%20Swiss",
"KangaROOS",
"Kanye%20West",
"Kapital",
"KARA",
"Karhu",
"KAWS",
"Keiser%20Clark",
"Kenzo",
"Khaite",
"Kids%20Of%20Immigrants",
"KidSuper",
"Kiko%20Kostadinov",
"Kith",
"Know%20Wave",
"Ksubi",
"Lanvin",
"Le%20Coq%20Sportif",
"Lemaire",
"Les%20Tien",
"levis",
"li%20ning",
"Liberaiders",
"Little%20Africa",
"Loewe",
"Lotto",
"Louis%20Vuitton",
"Maison%20Kitsuné",
"Maison%20Margiela",
"Maison%20Mihara%20Yasuhiro",
"Marc%20Jacobs",
"Marcelo%20Burlon",
"Marine%20Serre",
"Market",
"Marni",
"Martine%20Ali",
"Martine%20Rose",
"Mastermind",
"Mastermind%20World",
"MCQ",
"MediCom%20Toy",
"mercedes%20benz",
"Merrell",
"Midnight%20Studios",
"MISBHV",
"Mister%20Green",
"mitchell%20ness",
"Miu%20Miu",
"Mizuno",
"MM6%20Maison%20Margiela",
"Molly%20Goddard",
"Moncler",
"Moncler%20Genius",
"Moncler%20Grenoble",
"Movies",
"Mowalola",
"mr%20saturday",
"MSCHF",
"Mugler",
"museum%20of%20peace%20quiet",
"Music",
"Mykita",
"Nahmias",
"Nanamica",
"Needles",
"Neighborhood",
"New%20Balance",
"New%20Era",
"Nike",
"Noah",
"Norse%20Projects",
"Nowhere",
"number%20nine",
"OAMC",
"off%20white",
"ON",
"One%20Of%20These%20Days",
"Onitsuka%20Tiger",
"Online%20Ceramics",
"Other",
"Ottolinger",
"OVO",
"Paco%20Rabanne",
"Palace",
"Palm%20Angels",
"pam",
"Paperboy",
"paris%20saint%20germain",
"Parra",
"Patta",
"Peter%20Do",
"PF%20Flyers",
"Pierre%20Hardy",
"Pleasures",
"Pleats%20Please%20Issey%20Miyake",
"Poche",
"Polite%20Worldwide",
"Polo%20By%20Ralph%20Lauren",
"Polo%20Ralph%20Lauren",
"porter%20yoshida%20co",
"Prada",
"Psychworld",
"Puma",
"Quiet%20Golf",
"Raf%20Simons",
"Rassvet",
"READYMADE",
"Real%20Bad%20Man",
"redone",
"Reebok",
"Reese%20Cooper",
"RetroSuperFuture",
"Rhude",
"Rick%20Owens",
"Rick%20Owens%20DRKSHDW",
"Sacai",
"Saint%20Laurent",
"Saint%20Michael",
"Saintwoods",
"Salomon",
"Sandal%20Boyz",
"Sandy%20Liang",
"Saucony",
"Siberia%20Hills",
"Sies%20Marjan",
"Simone%20Rocha",
"Sinclair",
"Skim%20Milk",
"Sky%20High%20Farm",
"SLVRLAKE",
"Song%20For%20The%20Mute",
"Sony",
"Sophie%20Bille%20Brahe",
"Soulland",
"Sp5der",
"Sports",
"Sporty%20&%20Rich",
"Stand%20Studio",
"Stone%20Island",
"Stone%20Island%20Shadow%20Project",
"Students",
"Stussy",
"Suicoke",
"Sulvam",
"SUPER%20By%20RetroSuperFuture",
"Supra",
"Supreme",
"T%20By%20Alexander%20Wang",
"Taiga%20Takahashi",
"tao%20comme%20des%20garcons",
"The%20Hundreds",
"The%20North%20Face",
"The%20Source",
"Thisisneverthat",
"Tier",
"Timberland",
"Tom%20Sachs",
"Tommy%20Hilfiger",
"Total%20Luxury%20Spa",
"Travis%20Scott",
"tricot%20comme%20des%20garcons",
"TV",
"Ubiq",
"Umbro",
"Under%20Armour",
"Undercover",
"Used%20Future",
"Valentino",
"Vans",
"VEERT",
"Veneda%20Carter",
"Versace",
"Vetements",
"Vintage",
"Visvim",
"Vivienne%20Westwood",
"Vlone",
"VTMNTS",
"Wacko%20Maria",
"Wales%20Bonner",
"We11done",
"Who%20Decides%20War",
"WHOLE",
"y%203",
"Yamborghini",
"Yeezy",
"Yeezy%20Gap",
"Yeezy%20Gap%20Engineered%20By%20Balenciaga",
"Yohji%20Yamamoto",
"Yohji%20Yamamoto%20Pour%20Homme",
"yproject",
"ys",]