# Generated by Django 3.2.12 on 2022-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=300)),
                ('colorway', models.CharField(max_length=150)),
                ('countryOfManufacture', models.CharField(max_length=100)),
                ('dataType', models.CharField(default='product', max_length=100)),
                ('describtion', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('productCategory', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('retailPrice', models.PositiveBigIntegerField()),
                ('shoe', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('styleId', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=500)),
                ('smallImageUrl', models.CharField(max_length=500)),
                ('thumbUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
