# Generated by Django 3.2.12 on 2022-11-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kicks',
            old_name='describtion',
            new_name='description',
        ),
    ]
