# Generated by Django 3.2.12 on 2022-11-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_describtion_kicks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='dataType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kicks',
            name='releaseDate',
            field=models.CharField(max_length=100),
        ),
    ]
