# Generated by Django 3.2.12 on 2022-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221118_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='shoe',
            field=models.CharField(max_length=500),
        ),
    ]
