# Generated by Django 3.2.12 on 2022-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_kicks_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='estimatedMarketValue',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kicks',
            name='sku',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
