# Generated by Django 3.2.12 on 2022-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221118_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='local_imageUrl',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='kicks',
            name='local_smallImageUrl',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='kicks',
            name='local_thumbUrl',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
