# Generated by Django 3.2.12 on 2022-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221121_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='local_imageUrl',
            field=models.CharField(default='http://localhost:8000/media/images/defaultImg.png', max_length=500),
        ),
    ]
