# Generated by Django 3.2.12 on 2022-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_kicks_local_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='local_imageUrl',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
