# Generated by Django 3.2.12 on 2022-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_kicks_local_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
