# Generated by Django 3.2.12 on 2022-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20221210_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='slug',
            field=models.CharField(default='', max_length=500),
        ),
    ]
