# Generated by Django 3.2.12 on 2022-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_kicks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='retailPriceKrw',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
