# Generated by Django 3.2.12 on 2022-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_kicks_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='release_date_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
