# Generated by Django 3.2.12 on 2022-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20221210_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='sku',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
